plugins {
	id 'net.fabricmc.fabric-loom' version '1.18.2'
}

version = '0.1.0+mc26.1.2'
group = 'mimic'
base {
	archivesName = 'mimic-pvp'
}

dependencies {
	minecraft 'com.mojang:minecraft:26.1.2'
	implementation 'net.fabricmc:fabric-loader:0.19.5'
	implementation 'net.fabricmc.fabric-api:fabric-api:0.155.3+26.1.2'
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}
